### ISSUE TITLE
Why is an line here....[has snapshot]

### ISSUE THREAD

**Issue by leeeboo** [tmdvs/TDBadgedCell#53]
Default tableviewcontroller;
Basic tableviewcell;

[cell.textLabel setText:group.name];
[cell.detailTextLabel setText:[NSString stringWithFormat:@"%ld", (long)group.count]];

![2014-03-29 20 35 50](https://cloud.githubusercontent.com/assets/877939/2558297/dd0f587a-b73f-11e3-8077-d3dbd3178a4d.png)

**Comment by bachle** [comment]
@tmdvs I'm still having issues with this. Also forcing the cell's background color to a different color isn't helping. I've tried white, yellow, etc. 

![screen shot 2015-04-15 at 1 32 23 pm 1](https://cloud.githubusercontent.com/assets/517115/7168647/e75d7b8e-e373-11e4-9391-e46da160f9bc.png)

**Comment by dixiedream** [comment]
Putting a white background on the table view's cell solved the problem. At least for me.
