### ISSUE TITLE
Vertical line near badge

### ISSUE THREAD

**Issue by dixiedream** [tmdvs/TDBadgedCell#65]
Why i've got this issue with the badge? It's something related to the title field?
![img_3538](https://cloud.githubusercontent.com/assets/7778930/9871656/633cbdc0-5b95-11e5-8b2b-995c09e9f9dc.jpg)

Thanks

**Comment by tmdvs** [comment]
A few people have experience this when using a transparent cell background. There is no code within the class that seems to draw this line, however using a white background seems to address the issue.

[See this comment](https://github.com/tmdvs/TDBadgedCell/issues/53#issuecomment-54793720)
