### ISSUE TITLE
podspec needs update?

### ISSUE THREAD

**Issue by T-Pham** [tmdvs/TDBadgedCell#68]
The current [podspec on CocoaPods](https://github.com/CocoaPods/Specs/blob/master/Specs/TDBadgedCell/3.0/TDBadgedCell.podspec.json) has a wrong `source_files` path and points to the old version 3.0.
Also, the podspec file is not on this GitHub repo either.

Could you please provide a fix for this? Thanks.

**Comment by tmdvs** [comment]
Merged.

**Comment by tielur** [comment]
So if we were using the "old" 3.0 we should change now to 2.6? This change is breaking for people that were using the cocoapod before this updated it.

**Comment by tmdvs** [comment]
You're right, this podspec isnt right. I'll look into updating it as soon as I can.

**Comment by guidev** [comment]
cocoa pods still shows 3.0 as the last version : https://github.com/CocoaPods/Specs/tree/master/Specs/1/3/9/TDBadgedCell

**Comment by fulldecent** [comment]
Related #71

**Comment by fulldecent** [comment]
Note to anyone else that needs this to work today:

    pod 'TDBadgedCell', '~> 2.0'

^^ This works for me.
