### ISSUE TITLE
TDBadgedCell performance issue

### ISSUE THREAD

**Issue by KanybekMomukeyev** [tmdvs/TDBadgedCell#73]
Only want to ask question: 
When scrolling tableView, while there is a badge on cell, there is serious performance issue, flickering, and it's sometimes annoying. Any solution of this 

```
private func drawBadge()
```

**Comment by tmdvs** [comment]
I've just run a test app with 500 badge cells and I was able to scroll without any visual lag. Can you confirm there is nothing blocking the main thread in your datasource cellForRowAt: method which could be causing flicking/delayed drawing?

**Comment by KanybekMomukeyev** [comment]
@tmdvs now will try to profile and find exactly what cause this issue

**Comment by KanybekMomukeyev** [comment]
@tmdvs something wrong with my xcode 8.2 instruments profiler, Time Profiler did not showing methods, only memory adress, will continue search, but exactly flickering there, where is a badge, on ipad mini 1, ios 9.3

**Comment by tmdvs** [comment]
I'm closing this issue for now, however I will re-open it should the issue become replicable!

**Comment by KanybekMomukeyev** [comment]
@tmdvs 
<img width="946" alt="screen shot 2017-02-23 at 09 51 46" src="https://cloud.githubusercontent.com/assets/866641/23244398/14e356c0-f9af-11e6-9248-139e7bd4949b.png">

Here is shown on my ipad mini 1
And i understand why this is happening, here on [stackoverflow](http://stackoverflow.com/questions/5401226/uitableviewcell-selector-setselectedanimated-gets-called-many-times) say than on scroll 
`setHighlighted` and `setSelected` calling many times, so `drawBadge()` calling many times!
