### ISSUE TITLE
Text is cut off

### ISSUE THREAD

**Issue by fulldecent** [tmdvs/TDBadgedCell#78]
I just upgraded from TDBadgedCell from version 2.0 to 5.0. (Why so slow? Because [the "optimistic version operator" is stupid](https://github.com/rubygems/rubygems/issues/1919)).

Now text is my cells is cut off:

![screen shot 2017-10-05 at 6 31 35 pm](https://user-images.githubusercontent.com/382183/31255815-d54e204a-a9fc-11e7-984a-d92ee10d46a2.png)

**Comment by tmdvs** [comment]
I've now published version 5.2 (215e1a6) which updates the code in layoutSubviews to correctly size the table cell labels when detailTextLabel is present.
