### ISSUE TITLE
Dynamic Type Support

### ISSUE THREAD

**Issue by CMoebius** [tmdvs/TDBadgedCell#82]
I am converting a project to support dynamic type and it would be great to have this supported. I can fork the project and create a PR, but I can't wait terribly long to have ti reviewed since this project is time sensitive. Thoughts?

**Comment by tmdvs** [comment]
I think this is a great idea! 

(I aim to get most feature pull requests merged within a day at most.)

**Comment by CMoebius** [comment]
Pull request submitted.

**Comment by tmdvs** [comment]
Thank you for implementing this. I've merged the pull request, and I have released a new version (v5.3.0) via CocoaPods so that people can opt into this change.
