### ISSUE TITLE
Swift 4.2 errors

### ISSUE THREAD

**Issue by TheFlow95** [tmdvs/TDBadgedCell#86]
There are many renamed classes in Swift 4.2 so you need to update the project. Here is the list:
* `UIFontTextStyle` has been renamed to `UIFont.TextStyle`
* `NSAttributedStringKey` has been renamed to `NSAttributedString.Key`

Thanks!

**Comment by tmdvs** [comment]
This has been addressed via #85 and available in [5.4.0](https://github.com/tmdvs/TDBadgedCell/releases/tag/v5.4.0)
